### ISSUE TITLE
Need The Windows platform

### ISSUE THREAD

**Issue by Orgbrat** [sthewissen/Plugin.Maui.DebugRainbows#1]
Steven, I have used this library for years with Xamarin Forms. Have been waiting for the Maui version and here it is except NO windows version. Please get windows added as soon as possible please. Keep up the good work. And great library...

Orgbrat

**Comment by sthewissen** [comment]
The rainbow background colors is a fairly straightforward fix. The debug grid could be tricky, especially with me not owning a Windows machine. I'll see what I can do to at least enable the background color bits for Windows in the next release.
